import Head from 'next/head';

const GlobalHeadTag = ({ title }) => {
    return (
        <Head>
            <title>{title}</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="description" content="Hulu Clone 2.0 Created By Me: Omar Hassan" />
            <link rel="icon" href="/favicon.png" />
        </Head>
    );
};

export default GlobalHeadTag;
